# Generated by Django 5.2 on 2025-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('type', models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement'), ('Terrain', 'Terrain'), ('Bureau', 'Bureau')], max_length=20)),
                ('statut', models.CharField(choices=[('À vendre', 'À vendre'), ('À louer', 'À louer'), ('Vendu', 'Vendu'), ('Loué', 'Loué')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='biens_photos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('ville', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
