# Generated by Django 5.1.5 on 2025-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='date_ajout',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='superficie',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='ville',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='titre',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='statut',
        ),
        migrations.AddField(
            model_name='bien',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented')], default='for_sale', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('office', 'Office')], max_length=20),
        ),
    ]
