# Generated by Django 5.1.5 on 2025-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_rename_date_ajout_bien_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='bedroom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bien',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
