# Generated by Django 5.1.5 on 2025-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_bien_bedroom_bien_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
