# Generated by Django 5.2 on 2025-04-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('Prévu', 'Prévu'), ('Réalisé', 'Réalisé'), ('Annulé', 'Annulé')], default='Prévu', max_length=20)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
