# Generated by Django 5.2 on 2025-04-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_photo'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='commentaire',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bien',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_client',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='type_interaction',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Tenant', 'Tenant')], default='Buyer', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_clients', to='biens.bien'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Visit', 'Visit'), ('Meeting', 'Meeting'), ('Note', 'Note')], default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
